In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd

from radp.digital_twin.utils.gis_tools import GISTools

In [3]:
simple_ue = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/UE_data_20UE_100ticks.csv')
topology = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/topology.csv')

In [4]:
simple_ue.drop(columns=['mock_ue_id', 'tick'], inplace=True)
simple_ue

       longitude   latitude
0     -22.625309  59.806764
1     119.764151  54.857584
2      72.095437 -20.253892
3     -67.548009 -38.100941
4      59.867089 -83.103930
...          ...        ...
1995   45.564260  42.609846
1996  132.457280  17.241235
1997 -101.217659  72.295988
1998  -16.480045 -26.656397
1999   34.222834  63.970820

[2000 rows x 2 columns]

In [5]:
def f0(data,topology):
    if topology["cell_id"].dtype == object:
            topology["cell_id"] = (
                topology["cell_id"].str.replace("cell_", "").astype(int)
            )
    data["key"] = 1
    topology["key"] = 1
    combined_df = pd.merge(data, topology, on="key").drop("key", axis=1)
    return combined_df

In [6]:
cartesian_df = f0(simple_ue, topology)

In [7]:
def f3(cartesian_df):
    cartesian_df["relative_bearing"] = cartesian_df.apply(
        lambda row: GISTools.get_relative_bearing(
            row["cell_az_deg"],
            row["cell_lat"],
            row["cell_lon"],
            row["latitude"],
            row["longitude"],
        ),
        axis=1,
    )
    return cartesian_df

In [8]:
f3(cartesian_df)

,longitude,latitude,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,relative_bearing
0,-22.625309,59.806764,35.690556,139.691944,1,0,2100,351.153872
1,-22.625309,59.806764,35.690556,139.691944,2,120,2100,231.153872
2,-22.625309,59.806764,35.690556,139.691944,3,240,2100,111.153872
3,119.764151,54.857584,35.690556,139.691944,1,0,2100,330.617727
4,119.764151,54.857584,35.690556,139.691944,2,120,2100,210.617727
...,...,...,...,...,...,...,...,...
5995,-16.480045,-26.656397,35.690556,139.691944,2,120,2100,167.318054
5996,-16.480045,-26.656397,35.690556,139.691944,3,240,2100,47.318054
5997,34.222834,63.970820,35.690556,139.691944,1,0,2100,332.079388
5998,34.222834,63.970820,35.690556,139.691944,2,120,2100,212.079388
5999,34.222834,63.970820,35.690556,139.691944,3,240,2100,92.079388