In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
from notebooks.radp_library import (preprocess_ue_data)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO
from apps.mobility_robustness_optimization.mro_rl import ReinforcedMRO

In [3]:
simple_ue = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/UE_data_20UE_100ticks.csv')
topology = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/topology.csv')
topology.loc[topology["cell_id"] == "cell_1", "cell_lat"] = -90
topology.loc[topology["cell_id"] == "cell_2", "cell_lat"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lat"] = 90

topology.loc[topology["cell_id"] == "cell_1", "cell_lon"] = -180
topology.loc[topology["cell_id"] == "cell_2", "cell_lon"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lon"] = 180

topology.loc[topology["cell_id"] == "cell_1", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_2", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_3", "cell_carrier_freq_mhz"] = 2100

simple_ue.drop(columns=['mock_ue_id', 'tick'], inplace=True)
simple_ue

       longitude   latitude
0     -22.625309  59.806764
1     119.764151  54.857584
2      72.095437 -20.253892
3     -67.548009 -38.100941
4      59.867089 -83.103930
...          ...        ...
1995   45.564260  42.609846
1996  132.457280  17.241235
1997 -101.217659  72.295988
1998  -16.480045 -26.656397
1999   34.222834  63.970820

[2000 rows x 2 columns]

In [4]:
topology

   cell_lat  cell_lon cell_id  cell_az_deg  cell_carrier_freq_mhz
0     -90.0    -180.0  cell_1            0                   2100
1       0.0       0.0  cell_2          120                   2100
2      90.0     180.0  cell_3          240                   2100

In [5]:
params = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 100,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 5,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 5,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 5,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.5,
                    "variance": 0.8,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

__Start__

In [ ]:
input_data = preprocess_ue_data(simple_ue, topology)
input_data

### Simple MRO

__init__

In [ ]:
mro = SimpleMRO(mobility_model_params = params, topology = topology)

__update__

In [ ]:
mro.train_or_update_rf_twin(input_data)

In [ ]:
mro.bayesian_digital_twins

__solve__

In [ ]:
mro.solve()

In [ ]:
mro.solve()

In [ ]:
mro.train_or_update_rf_twin(input_data)

### RL MRO

In [6]:
rl_mro = ReinforcedMRO(mobility_model_params = params, topology = topology)

In [7]:
input_data = preprocess_ue_data(simple_ue, topology)

In [8]:
rl_mro.train_or_update_rf_twin(input_data)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-05-10 14:46:45,281] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)
[2025-05-10 14:46:45,411] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019080)
[2025-05-10 14:46:45,542] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019099)
[2025-05-10 14:46:45,667] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019149)
[2025-05-10 14:46:45,793] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019228)
[2025-05-10 14:46:45,920] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019358)
[2025-05-10 14:46:46,056] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019524)
[2025-05-10 14:46:46,180] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019726)
[2025-05-10 14:46:46,307] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019924)
[2025-05-10 14:46:46,433] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020141)
[2025-05-10 14:46:46,565] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020347)
[2025-05-10 14:46:46,692] INFO:  Iter 12/100 - Loss: 0.568 (delta=-0.020519)
[2025-05-10 14:46:46,818] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020752)
[2025-05-10 14:46:46,946] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020919)
[2025-05-10 14:46:47,077] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021085)
[2025-05-10 14:46:47,200] INFO:  Iter 16/100 - Loss: 0.483 (delta=-0.021268)
[2025-05-10 14:46:47,334] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021436)
[2025-05-10 14:46:47,461] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021614)
[2025-05-10 14:46:47,590] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021799)
[2025-05-10 14:46:47,715] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021964)
[2025-05-10 14:46:47,844] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022139)
[2025-05-10 14:46:47,974] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022319)
[2025-05-10 14:46:48,104] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022491)
[2025-05-10 14:46:48,231] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022660)
[2025-05-10 14:46:48,357] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022829)
[2025-05-10 14:46:48,483] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.023005)
[2025-05-10 14:46:48,611] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023170)
[2025-05-10 14:46:48,733] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023322)
[2025-05-10 14:46:48,861] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023495)
[2025-05-10 14:46:48,985] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023647)
[2025-05-10 14:46:49,113] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023807)
[2025-05-10 14:46:49,241] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023969)
[2025-05-10 14:46:49,380] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024130)
[2025-05-10 14:46:49,509] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024263)
[2025-05-10 14:46:49,636] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024450)
[2025-05-10 14:46:49,765] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024596)
[2025-05-10 14:46:49,894] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024735)
[2025-05-10 14:46:50,022] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024963)
[2025-05-10 14:46:50,144] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.024988)
[2025-05-10 14:46:50,268] INFO:  Iter 40/100 - Loss: -0.077 (delta=-0.025106)
[2025-05-10 14:46:50,390] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025265)
[2025-05-10 14:46:50,513] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025278)
[2025-05-10 14:46:50,636] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025390)
[2025-05-10 14:46:50,769] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025384)
[2025-05-10 14:46:50,906] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025440)
[2025-05-10 14:46:51,037] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025630)
[2025-05-10 14:46:51,165] INFO:  Iter 47/100 - Loss: -0.255 (delta=-0.025600)
[2025-05-10 14:46:51,296] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025857)
[2025-05-10 14:46:51,419] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.025789)
[2025-05-10 14:46:51,541] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.026120)
[2025-05-10 14:46:51,664] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.026035)
[2025-05-10 14:46:51,785] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.025916)
[2025-05-10 14:46:51,908] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.026126)
[2025-05-10 14:46:52,035] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026092)
[2025-05-10 14:46:52,164] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026250)
[2025-05-10 14:46:52,279] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026108)
[2025-05-10 14:46:52,406] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026197)
[2025-05-10 14:46:52,532] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026482)
[2025-05-10 14:46:52,658] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026221)
[2025-05-10 14:46:52,780] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026347)
[2025-05-10 14:46:52,951] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026330)
[2025-05-10 14:46:53,076] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026542)
[2025-05-10 14:46:53,200] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026365)
[2025-05-10 14:46:53,323] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.026516)
[2025-05-10 14:46:53,450] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026386)
[2025-05-10 14:46:53,573] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026401)
[2025-05-10 14:46:53,700] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026182)
[2025-05-10 14:46:53,824] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026785)
[2025-05-10 14:46:53,950] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026364)
[2025-05-10 14:46:54,082] INFO:  Iter 70/100 - Loss: -0.859 (delta=-0.026375)
[2025-05-10 14:46:54,205] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026693)
[2025-05-10 14:46:54,332] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026216)
[2025-05-10 14:46:54,477] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026544)
[2025-05-10 14:46:54,614] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026608)
[2025-05-10 14:46:54,752] INFO:  Iter 75/100 - Loss: -0.991 (delta=-0.026214)
[2025-05-10 14:46:54,885] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026977)
[2025-05-10 14:46:55,022] INFO:  Iter 77/100 - Loss: -1.045 (delta=-0.026359)
[2025-05-10 14:46:55,150] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026438)
[2025-05-10 14:46:55,276] INFO:  Iter 79/100 - Loss: -1.098 (delta=-0.026303)
[2025-05-10 14:46:55,404] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026370)
[2025-05-10 14:46:55,532] INFO:  Iter 81/100 - Loss: -1.150 (delta=-0.026509)
[2025-05-10 14:46:55,652] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.026231)
[2025-05-10 14:46:55,781] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.026535)
[2025-05-10 14:46:55,912] INFO:  Iter 84/100 - Loss: -1.229 (delta=-0.026263)
[2025-05-10 14:46:56,053] INFO:  Iter 85/100 - Loss: -1.256 (delta=-0.026143)
[2025-05-10 14:46:56,229] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026720)
[2025-05-10 14:46:56,382] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026013)
[2025-05-10 14:46:56,514] INFO:  Iter 88/100 - Loss: -1.334 (delta=-0.026138)
[2025-05-10 14:46:56,645] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026370)
[2025-05-10 14:46:56,773] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.026033)
[2025-05-10 14:46:56,904] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.026245)
[2025-05-10 14:46:57,034] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.026118)
[2025-05-10 14:46:57,165] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.025976)
[2025-05-10 14:46:57,294] INFO:  Iter 94/100 - Loss: -1.491 (delta=-0.026113)
[2025-05-10 14:46:57,427] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.025704)
[2025-05-10 14:46:57,559] INFO:  Iter 96/100 - Loss: -1.543 (delta=-0.025915)
[2025-05-10 14:46:57,690] INFO:  Iter 97/100 - Loss: -1.569 (delta=-0.026092)
[2025-05-10 14:46:57,823] INFO:  Iter 98/100 - Loss: -1.595 (delta=-0.025606)
[2025-05-10 14:46:57,959] INFO:  Iter 99/100 - Loss: -1.621 (delta=-0.026350)
[2025-05-10 14:46:58,089] INFO:  Iter 100/100 - Loss: -1.646 (delta=-0.025252)
[2025-05-10 14:46:58,241] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-05-10 14:46:58,367] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018671)
[2025-05-10 14:46:58,496] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018732)
[2025-05-10 14:46:58,624] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018822)
[2025-05-10 14:46:58,747] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018948)
[2025-05-10 14:46:58,876] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019099)
[2025-05-10 14:46:59,000] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019287)
[2025-05-10 14:46:59,122] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019500)
[2025-05-10 14:46:59,248] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019694)
[2025-05-10 14:46:59,374] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019902)
[2025-05-10 14:46:59,494] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020104)
[2025-05-10 14:46:59,620] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020320)
[2025-05-10 14:46:59,745] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020485)
[2025-05-10 14:46:59,873] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020707)
[2025-05-10 14:47:00,001] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020890)
[2025-05-10 14:47:00,129] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021088)
[2025-05-10 14:47:00,257] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021252)
[2025-05-10 14:47:00,383] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021468)
[2025-05-10 14:47:00,509] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021641)
[2025-05-10 14:47:00,634] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021818)
[2025-05-10 14:47:00,759] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022002)
[2025-05-10 14:47:00,878] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022182)
[2025-05-10 14:47:01,006] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022354)
[2025-05-10 14:47:01,132] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022534)
[2025-05-10 14:47:01,258] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022707)
[2025-05-10 14:47:01,387] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022871)
[2025-05-10 14:47:01,504] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023042)
[2025-05-10 14:47:01,625] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023201)
[2025-05-10 14:47:01,746] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023361)
[2025-05-10 14:47:01,869] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023509)
[2025-05-10 14:47:01,993] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023665)
[2025-05-10 14:47:02,118] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023807)
[2025-05-10 14:47:02,237] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023947)
[2025-05-10 14:47:02,360] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024085)
[2025-05-10 14:47:02,487] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024213)
[2025-05-10 14:47:02,608] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024341)
[2025-05-10 14:47:02,731] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024469)
[2025-05-10 14:47:02,854] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024580)
[2025-05-10 14:47:02,982] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024695)
[2025-05-10 14:47:03,109] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024806)
[2025-05-10 14:47:03,233] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024911)
[2025-05-10 14:47:03,358] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.024998)
[2025-05-10 14:47:03,478] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025095)
[2025-05-10 14:47:03,600] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025196)
[2025-05-10 14:47:03,716] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025278)
[2025-05-10 14:47:03,836] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025353)
[2025-05-10 14:47:03,961] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025437)
[2025-05-10 14:47:04,087] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025519)
[2025-05-10 14:47:04,213] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025583)
[2025-05-10 14:47:04,336] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025634)
[2025-05-10 14:47:04,460] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025706)
[2025-05-10 14:47:04,583] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025763)
[2025-05-10 14:47:04,713] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025818)
[2025-05-10 14:47:04,839] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025862)
[2025-05-10 14:47:04,962] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025918)
[2025-05-10 14:47:05,081] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025952)
[2025-05-10 14:47:05,209] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.025999)
[2025-05-10 14:47:05,335] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026030)
[2025-05-10 14:47:05,462] INFO:  Iter 59/100 - Loss: -0.578 (delta=-0.026087)
[2025-05-10 14:47:05,590] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026108)
[2025-05-10 14:47:05,715] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026124)
[2025-05-10 14:47:05,834] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026179)
[2025-05-10 14:47:05,961] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026187)
[2025-05-10 14:47:06,091] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026207)
[2025-05-10 14:47:06,212] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026301)
[2025-05-10 14:47:06,336] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026299)
[2025-05-10 14:47:06,455] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026297)
[2025-05-10 14:47:06,572] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026360)
[2025-05-10 14:47:06,698] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026436)
[2025-05-10 14:47:06,817] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026413)
[2025-05-10 14:47:06,958] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026510)
[2025-05-10 14:47:07,085] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026532)
[2025-05-10 14:47:07,208] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026445)
[2025-05-10 14:47:07,335] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026505)
[2025-05-10 14:47:07,460] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026396)
[2025-05-10 14:47:07,581] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026265)
[2025-05-10 14:47:07,700] INFO:  Iter 77/100 - Loss: -1.051 (delta=-0.026361)
[2025-05-10 14:47:07,829] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026261)
[2025-05-10 14:47:07,947] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026187)
[2025-05-10 14:47:08,072] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026511)
[2025-05-10 14:47:08,197] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026380)
[2025-05-10 14:47:08,324] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026248)
[2025-05-10 14:47:08,453] INFO:  Iter 83/100 - Loss: -1.209 (delta=-0.026418)
[2025-05-10 14:47:08,584] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026462)
[2025-05-10 14:47:08,708] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026135)
[2025-05-10 14:47:08,833] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026322)
[2025-05-10 14:47:08,956] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026277)
[2025-05-10 14:47:09,082] INFO:  Iter 88/100 - Loss: -1.341 (delta=-0.026089)
[2025-05-10 14:47:09,210] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026246)
[2025-05-10 14:47:09,337] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.025981)
[2025-05-10 14:47:09,460] INFO:  Iter 91/100 - Loss: -1.419 (delta=-0.026269)
[2025-05-10 14:47:09,584] INFO:  Iter 92/100 - Loss: -1.445 (delta=-0.025938)
[2025-05-10 14:47:09,713] INFO:  Iter 93/100 - Loss: -1.471 (delta=-0.026199)
[2025-05-10 14:47:09,837] INFO:  Iter 94/100 - Loss: -1.498 (delta=-0.026269)
[2025-05-10 14:47:09,960] INFO:  Iter 95/100 - Loss: nan (delta=nan)
[2025-05-10 14:47:10,088] INFO:  Iter 96/100 - Loss: nan (delta=nan)
[2025-05-10 14:47:10,215] INFO:  Iter 97/100 - Loss: -1.575 (delta=nan)
[2025-05-10 14:47:10,337] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-10 14:47:10,464] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-10 14:47:10,605] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-10 14:47:10,736] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-05-10 14:47:10,858] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019062)
[2025-05-10 14:47:10,979] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019109)
[2025-05-10 14:47:11,107] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019167)
[2025-05-10 14:47:11,222] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019244)
[2025-05-10 14:47:11,341] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019351)
[2025-05-10 14:47:11,463] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019484)
[2025-05-10 14:47:11,584] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019664)
[2025-05-10 14:47:11,700] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019875)
[2025-05-10 14:47:11,817] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020074)
[2025-05-10 14:47:11,946] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020275)
[2025-05-10 14:47:12,073] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020478)
[2025-05-10 14:47:12,195] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020688)
[2025-05-10 14:47:12,320] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020861)
[2025-05-10 14:47:12,448] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021065)
[2025-05-10 14:47:12,575] INFO:  Iter 16/100 - Loss: 0.479 (delta=-0.021220)
[2025-05-10 14:47:12,695] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021419)
[2025-05-10 14:47:12,820] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.021589)
[2025-05-10 14:47:12,946] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021765)
[2025-05-10 14:47:13,067] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021931)
[2025-05-10 14:47:13,192] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022101)
[2025-05-10 14:47:13,322] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022260)
[2025-05-10 14:47:13,446] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022442)
[2025-05-10 14:47:13,573] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022608)
[2025-05-10 14:47:13,697] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022769)
[2025-05-10 14:47:13,820] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022937)
[2025-05-10 14:47:13,943] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023101)
[2025-05-10 14:47:14,072] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023252)
[2025-05-10 14:47:14,196] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023404)
[2025-05-10 14:47:14,320] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023560)
[2025-05-10 14:47:14,446] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023703)
[2025-05-10 14:47:14,568] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023839)
[2025-05-10 14:47:14,695] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023975)
[2025-05-10 14:47:14,821] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024111)
[2025-05-10 14:47:14,948] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024249)
[2025-05-10 14:47:15,076] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024368)
[2025-05-10 14:47:15,202] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024504)
[2025-05-10 14:47:15,326] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024629)
[2025-05-10 14:47:15,454] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024751)
[2025-05-10 14:47:15,583] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024864)
[2025-05-10 14:47:15,712] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.025012)
[2025-05-10 14:47:15,835] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025114)
[2025-05-10 14:47:15,958] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025233)
[2025-05-10 14:47:16,079] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025371)
[2025-05-10 14:47:16,205] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025474)
[2025-05-10 14:47:16,334] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025630)
[2025-05-10 14:47:16,457] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025628)
[2025-05-10 14:47:16,598] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025779)
[2025-05-10 14:47:16,733] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025806)
[2025-05-10 14:47:16,864] INFO:  Iter 50/100 - Loss: -0.335 (delta=-0.025830)
[2025-05-10 14:47:16,997] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.025870)
[2025-05-10 14:47:17,128] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.026057)
[2025-05-10 14:47:17,249] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.025772)
[2025-05-10 14:47:17,376] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.026066)
[2025-05-10 14:47:17,497] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026100)
[2025-05-10 14:47:17,625] INFO:  Iter 56/100 - Loss: -0.491 (delta=-0.026161)
[2025-05-10 14:47:17,765] INFO:  Iter 57/100 - Loss: -0.517 (delta=-0.026242)
[2025-05-10 14:47:18,009] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.025893)
[2025-05-10 14:47:18,206] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026542)

In [9]:
input_data

     cell_id  log_distance  cell_rxpwr_dbm  relative_bearing
0     cell_1     16.629500     -100.311970        157.374691
1     cell_2     15.752768      -99.841523        227.382797
2     cell_3     15.027772      -99.432278        142.625309
3     cell_1     16.595905     -100.294405        299.764151
4     cell_2     16.289273     -100.132420        271.427214
...      ...           ...             ...               ...
5995  cell_2     15.054748      -99.447856         89.471165
5996  cell_3     16.379387     -100.180339        136.480045
5997  cell_1     16.656917     -100.326278        214.222834
5998  cell_2     15.850264      -99.895116        255.358234
5999  cell_3     14.879372      -99.346078         85.777166

[6000 rows x 4 columns]

In [ ]:
rl_mro.solve()

Using cpu device
Episode: 1, Timestep: 1, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False
Episode: 1, Timestep: 2, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False
Episode: 1, Timestep: 3, Hyst: 0.983610, TTT: 2, Reward: 100.000000, Done: False
Episode: 1, Timestep: 4, Hyst: 0.822099, TTT: 2, Reward: 100.000000, Done: False
Episode: 1, Timestep: 5, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False
Episode: 1, Timestep: 6, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False
Episode: 1, Timestep: 7, Hyst: 1.692606, TTT: 2, Reward: 100.000000, Done: False