In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
from notebooks.radp_library import (preprocess_ue_data)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO

In [3]:
simple_ue = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/UE_data_20UE_100ticks.csv')
topology = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/topology.csv')
topology.loc[topology["cell_id"] == "cell_1", "cell_lat"] = -90
topology.loc[topology["cell_id"] == "cell_2", "cell_lat"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lat"] = 90

topology.loc[topology["cell_id"] == "cell_1", "cell_lon"] = -180
topology.loc[topology["cell_id"] == "cell_2", "cell_lon"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lon"] = 180

topology.loc[topology["cell_id"] == "cell_1", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_2", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_3", "cell_carrier_freq_mhz"] = 2100

simple_ue.drop(columns=['mock_ue_id', 'tick'], inplace=True)
simple_ue

       longitude   latitude
0     -22.625309  59.806764
1     119.764151  54.857584
2      72.095437 -20.253892
3     -67.548009 -38.100941
4      59.867089 -83.103930
...          ...        ...
1995   45.564260  42.609846
1996  132.457280  17.241235
1997 -101.217659  72.295988
1998  -16.480045 -26.656397
1999   34.222834  63.970820

[2000 rows x 2 columns]

In [4]:
topology

   cell_lat  cell_lon cell_id  cell_az_deg  cell_carrier_freq_mhz
0     -90.0    -180.0  cell_1            0                   2100
1       0.0       0.0  cell_2          120                   2100
2      90.0     180.0  cell_3          240                   2100

In [5]:
input_data = preprocess_ue_data(simple_ue, topology)
input_data

,longitude,latitude,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,log_distance,cell_rxpwr_dbm
0,-22.625309,59.806764,-90.0,-180.0,1,0,2100,16.629500,-100.311970
1,-22.625309,59.806764,0.0,0.0,2,120,2100,15.752768,-99.841523
2,-22.625309,59.806764,90.0,180.0,3,240,2100,15.027772,-99.432278
3,119.764151,54.857584,-90.0,-180.0,1,0,2100,16.595905,-100.294405
4,119.764151,54.857584,0.0,0.0,2,120,2100,16.289273,-100.132420
...,...,...,...,...,...,...,...,...,...
5995,-16.480045,-26.656397,0.0,0.0,2,120,2100,15.054748,-99.447856
5996,-16.480045,-26.656397,90.0,180.0,3,240,2100,16.379387,-100.180339
5997,34.222834,63.970820,-90.0,-180.0,1,0,2100,16.656917,-100.326278
5998,34.222834,63.970820,0.0,0.0,2,120,2100,15.850264,-99.895116
5999,34.222834,63.970820,90.0,180.0,3,240,2100,14.879372,-99.346078

In [6]:
mro = SimpleMRO(simple_ue,topology)

In [7]:
mro.train_or_update_rf_twin(input_data)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-05-10 13:10:21,379] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)
[2025-05-10 13:10:21,545] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019081)
[2025-05-10 13:10:21,697] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019101)
[2025-05-10 13:10:21,849] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019147)
[2025-05-10 13:10:22,007] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019230)
[2025-05-10 13:10:22,151] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019357)
[2025-05-10 13:10:22,301] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019525)
[2025-05-10 13:10:22,452] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019724)
[2025-05-10 13:10:22,597] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019936)
[2025-05-10 13:10:22,748] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020136)
[2025-05-10 13:10:22,892] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020334)
[2025-05-10 13:10:23,037] INFO:  Iter 12/100 - Loss: 0.567 (delta=-0.020549)
[2025-05-10 13:10:23,181] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020730)
[2025-05-10 13:10:23,323] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020911)
[2025-05-10 13:10:23,471] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021088)
[2025-05-10 13:10:23,653] INFO:  Iter 16/100 - Loss: 0.484 (delta=-0.021264)
[2025-05-10 13:10:23,808] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021442)
[2025-05-10 13:10:23,958] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021619)
[2025-05-10 13:10:24,109] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021795)
[2025-05-10 13:10:24,257] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021968)
[2025-05-10 13:10:24,406] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022136)
[2025-05-10 13:10:24,553] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022317)
[2025-05-10 13:10:24,703] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022490)
[2025-05-10 13:10:24,847] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022666)
[2025-05-10 13:10:24,986] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022835)
[2025-05-10 13:10:25,132] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.023003)
[2025-05-10 13:10:25,285] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023159)
[2025-05-10 13:10:25,428] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023333)
[2025-05-10 13:10:25,579] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023495)
[2025-05-10 13:10:25,714] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023635)
[2025-05-10 13:10:25,862] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023824)
[2025-05-10 13:10:26,010] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023946)
[2025-05-10 13:10:26,155] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024137)
[2025-05-10 13:10:26,303] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024293)
[2025-05-10 13:10:26,453] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024412)
[2025-05-10 13:10:26,606] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024616)
[2025-05-10 13:10:26,746] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024738)
[2025-05-10 13:10:26,885] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024883)
[2025-05-10 13:10:27,031] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.025068)
[2025-05-10 13:10:27,176] INFO:  Iter 40/100 - Loss: -0.077 (delta=-0.025162)
[2025-05-10 13:10:27,327] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025212)
[2025-05-10 13:10:27,476] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025297)
[2025-05-10 13:10:27,617] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025346)
[2025-05-10 13:10:27,764] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025452)
[2025-05-10 13:10:27,906] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025515)
[2025-05-10 13:10:28,055] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025302)
[2025-05-10 13:10:28,204] INFO:  Iter 47/100 - Loss: -0.256 (delta=-0.025920)
[2025-05-10 13:10:28,349] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025698)
[2025-05-10 13:10:28,496] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.025920)
[2025-05-10 13:10:28,647] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.026009)
[2025-05-10 13:10:28,788] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.025859)
[2025-05-10 13:10:28,926] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.026181)
[2025-05-10 13:10:29,069] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.025950)
[2025-05-10 13:10:29,221] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026233)
[2025-05-10 13:10:29,367] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026179)
[2025-05-10 13:10:29,514] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026103)
[2025-05-10 13:10:29,663] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026333)
[2025-05-10 13:10:29,854] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026290)
[2025-05-10 13:10:30,000] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026281)
[2025-05-10 13:10:30,150] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026436)
[2025-05-10 13:10:30,294] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026305)
[2025-05-10 13:10:30,462] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026310)
[2025-05-10 13:10:30,605] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026327)
[2025-05-10 13:10:30,748] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.026606)
[2025-05-10 13:10:30,895] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026523)
[2025-05-10 13:10:31,035] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026371)
[2025-05-10 13:10:31,184] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026585)
[2025-05-10 13:10:31,326] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026011)
[2025-05-10 13:10:31,466] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026886)
[2025-05-10 13:10:31,609] INFO:  Iter 70/100 - Loss: -0.859 (delta=-0.026455)
[2025-05-10 13:10:31,757] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026604)
[2025-05-10 13:10:31,899] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026375)
[2025-05-10 13:10:32,041] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026557)
[2025-05-10 13:10:32,189] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026343)
[2025-05-10 13:10:32,328] INFO:  Iter 75/100 - Loss: -0.992 (delta=-0.026594)
[2025-05-10 13:10:32,478] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026423)
[2025-05-10 13:10:32,627] INFO:  Iter 77/100 - Loss: -1.044 (delta=-0.026130)
[2025-05-10 13:10:32,773] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026682)
[2025-05-10 13:10:32,923] INFO:  Iter 79/100 - Loss: -1.097 (delta=-0.026389)
[2025-05-10 13:10:33,070] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026553)
[2025-05-10 13:10:33,215] INFO:  Iter 81/100 - Loss: -1.151 (delta=-0.026533)
[2025-05-10 13:10:33,366] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.025993)
[2025-05-10 13:10:33,510] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.026608)
[2025-05-10 13:10:33,654] INFO:  Iter 84/100 - Loss: -1.230 (delta=-0.026415)
[2025-05-10 13:10:33,802] INFO:  Iter 85/100 - Loss: -1.256 (delta=-0.026113)
[2025-05-10 13:10:33,944] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026495)
[2025-05-10 13:10:34,088] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026308)
[2025-05-10 13:10:34,234] INFO:  Iter 88/100 - Loss: -1.334 (delta=-0.025952)
[2025-05-10 13:10:34,379] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026274)
[2025-05-10 13:10:34,523] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.025900)
[2025-05-10 13:10:34,674] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.026492)
[2025-05-10 13:10:34,823] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.026393)
[2025-05-10 13:10:34,961] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.025555)
[2025-05-10 13:10:35,110] INFO:  Iter 94/100 - Loss: -1.491 (delta=-0.026209)
[2025-05-10 13:10:35,257] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.025777)
[2025-05-10 13:10:35,418] INFO:  Iter 96/100 - Loss: -1.543 (delta=-0.026433)
[2025-05-10 13:10:35,552] INFO:  Iter 97/100 - Loss: -1.569 (delta=-0.025749)
[2025-05-10 13:10:35,676] INFO:  Iter 98/100 - Loss: -1.595 (delta=-0.025510)
[2025-05-10 13:10:35,797] INFO:  Iter 99/100 - Loss: -1.621 (delta=-0.026284)
[2025-05-10 13:10:35,929] INFO:  Iter 100/100 - Loss: -1.646 (delta=-0.025358)
[2025-05-10 13:10:36,066] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-05-10 13:10:36,193] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018670)
[2025-05-10 13:10:36,314] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018730)
[2025-05-10 13:10:36,441] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018821)
[2025-05-10 13:10:36,570] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018946)
[2025-05-10 13:10:36,695] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019099)
[2025-05-10 13:10:36,822] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019296)
[2025-05-10 13:10:36,942] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019493)
[2025-05-10 13:10:37,068] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019695)
[2025-05-10 13:10:37,192] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019900)
[2025-05-10 13:10:37,321] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020107)
[2025-05-10 13:10:37,448] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020309)
[2025-05-10 13:10:37,573] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020508)
[2025-05-10 13:10:37,694] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020696)
[2025-05-10 13:10:37,812] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020892)
[2025-05-10 13:10:37,931] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021073)
[2025-05-10 13:10:38,059] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021275)
[2025-05-10 13:10:38,182] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021458)
[2025-05-10 13:10:38,304] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021637)
[2025-05-10 13:10:38,425] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021816)
[2025-05-10 13:10:38,549] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022003)
[2025-05-10 13:10:38,686] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022182)
[2025-05-10 13:10:38,814] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022352)
[2025-05-10 13:10:38,943] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022540)
[2025-05-10 13:10:39,066] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022701)
[2025-05-10 13:10:39,191] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022872)
[2025-05-10 13:10:39,310] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023045)
[2025-05-10 13:10:39,439] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023202)
[2025-05-10 13:10:39,560] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023358)
[2025-05-10 13:10:39,685] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023513)
[2025-05-10 13:10:39,813] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023665)
[2025-05-10 13:10:39,937] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023808)
[2025-05-10 13:10:40,060] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023950)
[2025-05-10 13:10:40,179] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024082)
[2025-05-10 13:10:40,299] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024213)
[2025-05-10 13:10:40,419] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024342)
[2025-05-10 13:10:40,548] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024462)
[2025-05-10 13:10:40,672] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024584)
[2025-05-10 13:10:40,800] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024695)
[2025-05-10 13:10:40,928] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024802)
[2025-05-10 13:10:41,054] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024910)
[2025-05-10 13:10:41,183] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.025003)
[2025-05-10 13:10:41,309] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025096)
[2025-05-10 13:10:41,440] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025197)
[2025-05-10 13:10:41,577] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025286)
[2025-05-10 13:10:41,705] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025352)
[2025-05-10 13:10:41,823] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025439)
[2025-05-10 13:10:41,944] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025512)
[2025-05-10 13:10:42,069] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025573)
[2025-05-10 13:10:42,193] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025644)
[2025-05-10 13:10:42,318] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025707)
[2025-05-10 13:10:42,443] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025767)
[2025-05-10 13:10:42,564] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025812)
[2025-05-10 13:10:42,692] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025868)
[2025-05-10 13:10:42,822] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025912)
[2025-05-10 13:10:42,976] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025959)
[2025-05-10 13:10:43,116] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.025987)
[2025-05-10 13:10:43,236] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026052)
[2025-05-10 13:10:43,367] INFO:  Iter 59/100 - Loss: -0.577 (delta=-0.026057)
[2025-05-10 13:10:43,510] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026110)
[2025-05-10 13:10:43,642] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026143)
[2025-05-10 13:10:43,764] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026145)
[2025-05-10 13:10:43,890] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026208)
[2025-05-10 13:10:44,031] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026222)
[2025-05-10 13:10:44,215] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026248)
[2025-05-10 13:10:44,347] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026317)
[2025-05-10 13:10:44,478] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026331)
[2025-05-10 13:10:44,613] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026360)
[2025-05-10 13:10:44,746] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026453)
[2025-05-10 13:10:44,880] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026424)
[2025-05-10 13:10:45,006] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026469)
[2025-05-10 13:10:45,132] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026575)
[2025-05-10 13:10:45,253] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026455)
[2025-05-10 13:10:45,370] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026434)
[2025-05-10 13:10:45,486] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026335)
[2025-05-10 13:10:45,604] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026385)
[2025-05-10 13:10:45,729] INFO:  Iter 77/100 - Loss: -1.052 (delta=-0.026397)
[2025-05-10 13:10:45,851] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026121)
[2025-05-10 13:10:45,990] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026391)
[2025-05-10 13:10:46,111] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026425)
[2025-05-10 13:10:46,243] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026297)
[2025-05-10 13:10:46,367] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026449)
[2025-05-10 13:10:46,494] INFO:  Iter 83/100 - Loss: -1.210 (delta=-0.026407)
[2025-05-10 13:10:46,607] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026259)
[2025-05-10 13:10:46,760] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026402)
[2025-05-10 13:10:46,885] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026083)
[2025-05-10 13:10:47,009] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026208)
[2025-05-10 13:10:47,139] INFO:  Iter 88/100 - Loss: -1.341 (delta=-0.026268)
[2025-05-10 13:10:47,266] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026200)
[2025-05-10 13:10:47,382] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.026200)
[2025-05-10 13:10:47,507] INFO:  Iter 91/100 - Loss: -1.419 (delta=-0.026032)
[2025-05-10 13:10:47,628] INFO:  Iter 92/100 - Loss: -1.445 (delta=-0.026065)
[2025-05-10 13:10:47,751] INFO:  Iter 93/100 - Loss: -1.472 (delta=-0.026202)
[2025-05-10 13:10:47,877] INFO:  Iter 94/100 - Loss: -1.498 (delta=-0.026088)
[2025-05-10 13:10:48,009] INFO:  Iter 95/100 - Loss: nan (delta=nan)
[2025-05-10 13:10:48,141] INFO:  Iter 96/100 - Loss: -1.549 (delta=nan)
[2025-05-10 13:10:48,266] INFO:  Iter 97/100 - Loss: -1.575 (delta=-0.026032)
[2025-05-10 13:10:48,393] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-10 13:10:48,509] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-10 13:10:48,628] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-10 13:10:48,768] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-05-10 13:10:48,892] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019065)
[2025-05-10 13:10:49,012] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019110)
[2025-05-10 13:10:49,146] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019167)
[2025-05-10 13:10:49,276] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019239)
[2025-05-10 13:10:49,395] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019353)
[2025-05-10 13:10:49,521] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019502)
[2025-05-10 13:10:49,639] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019656)
[2025-05-10 13:10:49,763] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019864)
[2025-05-10 13:10:49,885] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020077)
[2025-05-10 13:10:50,009] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020255)
[2025-05-10 13:10:50,133] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020488)
[2025-05-10 13:10:50,254] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020691)
[2025-05-10 13:10:50,368] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020872)
[2025-05-10 13:10:50,493] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021048)
[2025-05-10 13:10:50,614] INFO:  Iter 16/100 - Loss: 0.478 (delta=-0.021239)
[2025-05-10 13:10:50,750] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021408)
[2025-05-10 13:10:50,877] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.021591)
[2025-05-10 13:10:51,007] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021765)
[2025-05-10 13:10:51,146] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021927)
[2025-05-10 13:10:51,277] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022101)
[2025-05-10 13:10:51,404] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022270)
[2025-05-10 13:10:51,537] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022439)
[2025-05-10 13:10:51,671] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022615)
[2025-05-10 13:10:51,800] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022765)
[2025-05-10 13:10:51,940] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022936)
[2025-05-10 13:10:52,072] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023097)
[2025-05-10 13:10:52,200] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023251)
[2025-05-10 13:10:52,320] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023401)
[2025-05-10 13:10:52,447] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023562)
[2025-05-10 13:10:52,570] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023701)
[2025-05-10 13:10:52,692] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023841)
[2025-05-10 13:10:52,814] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023976)
[2025-05-10 13:10:52,984] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024125)
[2025-05-10 13:10:53,110] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024247)
[2025-05-10 13:10:53,236] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024367)
[2025-05-10 13:10:53,358] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024504)
[2025-05-10 13:10:53,487] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024628)
[2025-05-10 13:10:53,613] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024741)
[2025-05-10 13:10:53,737] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024879)
[2025-05-10 13:10:53,860] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.025004)
[2025-05-10 13:10:53,986] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025122)
[2025-05-10 13:10:54,110] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025237)
[2025-05-10 13:10:54,233] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025333)
[2025-05-10 13:10:54,363] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025518)
[2025-05-10 13:10:54,482] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025599)
[2025-05-10 13:10:54,627] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025713)
[2025-05-10 13:10:54,754] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025683)
[2025-05-10 13:10:54,878] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025780)
[2025-05-10 13:10:55,002] INFO:  Iter 50/100 - Loss: -0.334 (delta=-0.025859)
[2025-05-10 13:10:55,131] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.025956)
[2025-05-10 13:10:55,252] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.025787)
[2025-05-10 13:10:55,375] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.026103)
[2025-05-10 13:10:55,503] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.026150)
[2025-05-10 13:10:55,621] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.025532)
[2025-05-10 13:10:55,747] INFO:  Iter 56/100 - Loss: -0.491 (delta=-0.026529)
[2025-05-10 13:10:55,874] INFO:  Iter 57/100 - Loss: -0.517 (delta=-0.026001)
[2025-05-10 13:10:55,999] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.026017)

In [8]:
mro.bayesian_digital_twins

{1: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x256b948ce20>,
 2: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x25695d43700>,
 3: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x256b952e1f0>}